server:
  port: 5335

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: besiktasq7
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config_location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/repository/*.xml
  type-aliases-package: com.example.rr_company.model.entity

security:
  secret-key: CgTOA2QC9nxYspeBZBRsEIoDmsBbGTjfDCE6WfnOHHrA7rgHafqC5u1m6GL22pNY
  expiration: 30000000 #1000*60*5