server:
  port: 4343

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: besiktasq7
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config_location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/repository/*.xml
  type-aliases-package: com.example.rr_company.model.entity

security:
  secret-key: ui4woWU7Cfda2dUk02f3mDd6IrMHZQ4oNF324dakdl
  expiration: 300000 #1000*60*5